implemented describe_na_values and tests
UBC-MDS/edapython pull request #41
Opened 2020-03-05 01:47 UTC by v5y8

closes #30 
closes #32 
added dependencies and dev-dependencies

2020-03-05 07:08 UTC, sgauravm requested changes

2020-03-05 07:08 UTC, sgauravm commented on eda_analysis/eda_analysis.py
> +    return np.array([[0 if val else 1 for val in bool_array[col]] for col in bool_array.columns])
```suggestion
    na_val = np.array([[0 if val else 1 for val in bool_array[col]] for col in bool_array.columns])
    return pd.Series(data = np.sum(na_val!=1,axis=1),index = list(dataframe.columns))
```
OPTIONAL SUGGESTION:I really liked the one line logic you wrote for this function.But the array itself is not self explanatory. It is the same as finding the number of na values manually. You can return a series as suggested above. I tested that in my local by copying your function. You can use the suggested chunk or write your own logic,

2020-03-05 07:08 UTC, sgauravm commented on eda_analysis/eda_analysis.py
>          0 represents an NA value, 1 represents a non-NA value.
You can modify this according to the changes suggested in return of the function. This should nbe either pandas.Series or pandas.DataFrame

2020-03-05 07:08 UTC, sgauravm commented on eda_analysis/eda_analysis.py
>      '''
Include some defensive  coding like these :
```
    if not isinstance(dataframe, pd.DataFrame):
        raise Exception("The value of the argument 'dataframe' must be of type 'pandas.DataFrame'")
    
    if not isinstance(cat_vars,list) or not all(isinstance(x, str) for x in cat_vars):
        raise Exception("The value of the argument 'cat_vars' must be a list of strings")
```
Defensive coding is one of the requirement and even your test case should also have some negative testcase for these

2020-03-05 07:08 UTC, sgauravm commented on tests/test_eda_analysis.py
> +                                                                                               [0, 1]]))
If you are making the changes suggested in your main function, you might have to modify the test cases. Even if you are not making any changes in your main function then just add some test case for the exceptions case (Defensive coding).

2020-03-06 23:19 UTC, sgauravm commented on eda_analysis/eda_analysis.py
> +    return np.array([[0 if val else 1 for val in bool_array[col]] for col in bool_array.columns])
You can leave it for now as you will have to make changes in test file R function and its test. I am making it as an optional change

2020-03-07 01:22 UTC, v5y8 commented
@sgauravm I've made the changes; please take a look

2020-03-07 01:34 UTC, sgauravm approved these changes
Looks good . You can merge now

2020-03-07 17:09 UTC, merged